### ISSUE TITLE
/raspipass/config.ini is blank after saving any changes to Configuration

### ISSUE THREAD

**Issue by thejdlowe** [Pinchie/RaspiPass#12]
nano shows it as zero lines long and there is no data there; running update.php restores it to default, but even if I save it with no changes made, it goes back to blank. Even did sudo nano just to be safe that it wasn't some weird permissions issue.

It APPEARS to be something with save_config.php but I can't confirm it as I'm not too strong with PHP debugging, sadly.

**Comment by thejdlowe** [comment]
Appears to be potentially tied to Issue #8 as well.

**Comment by Pinchie** [comment]
@jdllama 
Confirmed - cause appears to be related to #8 - could you confirm whether this has been remedied by this week's 0.7.4 release?

**Comment by thejdlowe** [comment]
Perfectly fixed, thank you!
