### ISSUE TITLE
11.4e don"t work

### ISSUE THREAD

**Issue by the4anoni** [Pinchie/RaspiPass#21]
After format and updating to 11.4e homepass don't work.
AFAIK firewall blocks too much IPs.......

**Comment by Pinchie** [comment]
I popped up new iptables/firewall.rules files, and an accompanying image on the weekend. :)

Details in the reddit post [here](https://www.reddit.com/r/3DS/comments/68ddvk/just_a_quick_note_raspipass_firewall_update_after/). Re-open this ticket if it doesn't fix your issue. 👍
