### ISSUE TITLE
Assistance installing on a Pi Zero W

### ISSUE THREAD

**Issue by joshbgosh10592** [Pinchie/RaspiPass#33]
I wanted to move my RaspiPass solution over to a Pi Zero W for power reduction as well as to free up my Pi 3B.
However, when imaging using the pre-built image, it fails to bring up wlan0 (interface not found). I'm assuming this is because of the differences between the boards. however, I know Raspbian works perfectly fine on these.
I'm wondering if I can just install a blank Raspbian OS, and put all the scripts where they belong and bring it up.

Is there an easier way than copying everything over? And, where does everything actually go? If I can get this working, I'll take an image backup of it and can provide it to you, if you'd like.

**Comment by Pinchie** [comment]
It'll almost-definitely be a difference between the two boards.

The main thing the Pi Zero W *must* be able to do is bridge wlan0 and eth0 into br0.. that's the part I'm not sure of on that. 

I have my old guide that lists the network card setup [here](https://www.dropbox.com/s/sabrkriwir0fhwi/Raspipass%20Guide%20-%20Raspberry%20Pi%203.pdf?dl=0), as well as the software setup. Much of the software stuff is deprecated in favour of the code in the git repo and the install scripts there, but the br0 interface setup is the most crucial thing to get working.

That guide is also pre-web-interface, so you'll need Apache installed too.

Once I get my Pi 3 I'm keen to make an environment checking script that ensures all software is in place.. I'm also really keen to get a fresh image up on a newer version of Raspbian... but until then I think I might get a Zero W and have a fiddle this week. It'll let me test the scripting changes we're making, if I can get it working, and probably make the raspipass a bit cheaper too. Fingers crossed.

Let me know if you have any luck bridging. :)

**Comment by Pinchie** [comment]
To add, I just had to get a new power supply for my Pi3's battery backup, so I picked up a Zero W kit while it was on special while I was there. :)

Something to look at once I get the Pi3 one working again 😄
