### ISSUE TITLE
/raspipass/hostapd.conf is blank for some users

### ISSUE THREAD

**Issue by Pinchie** [Pinchie/RaspiPass#8]
Generates error _Interface name not specified in /run/hostapd.conf_
Inspection of /raspipass/hostapd.conf reveals an empty file
Inspection of /run/hostapd.conf is blank, excepting the SSID line appended by the RaspiPass script

Awaiting information on what settings are present before this issue & attempting to be applied when the issue occurs

Confirmed /raspipass/hostapd.conf in image is correctly populated

**Comment by Pinchie** [comment]
Still waiting on more info for this bug. In the meantime, the 'working' branch has all its config moved to /var/raspipass, but this shouldn't remedy this issue - the base /raspipass/hostapd.conf file is still generated as before.

**Comment by Oakman978** [comment]
Not sure if this is related, but from the raspipass website sometimes when I change a setting under the configuration tab, all of the settings change to the first option and I am unable to change them back. The only way I know to fix this is to re-burn the image file to the micro-SD card.

**Comment by Pinchie** [comment]
@Oakman978 
Could you confirm whether this issue has been remedied by the 0.7.4 release this week? It's aimed at resolving this issue, among others. :)

**Comment by Oakman978** [comment]
I haven't had any issues since this weeks release, thanks for being so quick to fix things 👍
